ALTER TABLE PENDING DROP CONSTRAINT FK_PENDING_DEPLOYMENT;
ALTER TABLE PENDING DROP CONSTRAINT FK_PENDING_RESOURCE;
alter table PARAMETER drop constraint FK1A96C389D4EBDE84;
drop table ACTION;
drop table PARAMETER;
DROP TABLE DEPLOYMENT;
DROP TABLE RESOURCE;
DROP TABLE PENDING;
